name: Main deploy workflow

on:
  push:
    branches:
      - branch-name

jobs:
  main:
    uses: mttzzz/github-deploy-template-workflow/.github/workflows/web-app.yml@master
    with:
      app_name: 'starter-pushka-biz'
      params: |
        app.port=3000
        app.domain=pushka.biz
        app.subdomain=starter
        app.useConfigMap=true
        app.livenessProbe.initialDelaySeconds=10
        app.readinessProbe.initialDelaySeconds=10
        app.probeScheme=HTTP
        app.probePath=/api/health
    secrets:
        BUILD_ARGS: ""
        HELM_REPO: ${{ secrets.HELM_REPO }}
        REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}